# Generated by Django 3.2.23 on 2024-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=255)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('travel_date', models.CharField(blank=True, max_length=255)),
                ('desination', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=255)),
                ('arrival_time', models.CharField(blank=True, max_length=255)),
                ('ar_class', models.CharField(blank=True, max_length=255)),
                ('baggage_allowance', models.CharField(blank=True, max_length=255)),
                ('issue_fare', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
