# Generated by Django 3.2.23 on 2024-01-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_news', '0003_auto_20240124_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='airline_name',
            new_name='flight',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='flight_num',
        ),
    ]
