# Generated by Django 3.2.23 on 2024-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_news', '0004_auto_20240124_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='passport_num',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
