# Generated by Django 3.2.23 on 2024-02-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_news', '0006_userdata_eticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='passport_num',
            new_name='passport_number',
        ),
    ]
