# Generated by Django 3.2.23 on 2024-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_news', '0007_rename_passport_num_userdata_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
